### ISSUE TITLE
There is not any `offset` on query to mongo callback

### ISSUE THREAD

**Issue by HMarzban** [pbatey/query-to-mongo#25]
Hi, in Document you point that after execration of `query-to-mongo` we get some object like this:
```js
{
  criteria: {
    name: 'john',
    age: { $gt: 21 }
  },
  options: {
    fields: { name: true, age: true },
    sort: { name: 1, age: -1 },
    offset: 10,
    limit: 10
  }
}
```
But in the case, there is not any offset when retrieving object:

```js
const q2m = require('query-to-mongo');
const queryString = "name=john&age>21&fields=name,age&sort=name,-age&offset=10&limit=10";
  
```

Give us the following object:
```js
{ 
   criteria: { name: 'john', age: { '$gt': 21 } },
   options:{ 
      fields: { name: 1, age: 1 },
      sort: { name: 1, age: -1 },
      skip: 10,
      limit: 10 
   },
   links: [Function: links] 
}
```
I think this `offset` must be changed to `skip` in the document. also as [mongodb ](https://docs.mongodb.com/manual/reference/method/db.collection.find/#set-the-starting-point-of-the-result-set), there is not `offset` key to execute it but we have `skip` keyword, even in [mongodb aggregation](https://docs.mongodb.com/manual/reference/operator/aggregation/skip/).

**Comment by pbatey** [comment]
I think the confusion is related to how/when I first developed and used this package. I was using [mongoskin](https://github.com/kissjs/node-mongoskin) to execute queries. _I see **mongoskin** hasn't been updated since 2016 -- Like I'm one to talk 😄 ._

At the time, **mongoskin** exposed a `find` method that accepted the criteria and options as-is. `db.Kitten.find(criteria, options).toArray(cb)`, for example.

I doubt the current version of **mongoskin** still support the options as-is. I believe it exposed `find` from a mongodb library. But it was _years_ ago -- I think it was before **MongoDB 3.0**.

Depending on the library you are using you'll likely need to cherry pick values from the returned options rather than passing it as-is.

My quick take on using a more up-to-date libarary ([Mongoose 6.0.0](https://mongoosejs.com/)) with results from **query-to-mongo**:
```
const mongoose = require('mongoose')
await mongoose.connect('mongodb://localhost:27017/test')
const kittySchema = new mongoose.Schema({
  name: String,
  age: Number,
})
const Kitten = mongoose.model('Kitten', kittySchema)

const queryString = "name=john&age>21&fields=name,age&sort=name,-age&offset=10&limit=10"
var q = q2m(queryString)

var query = Kitten.find(q.criteria)
if (q.options) {
  if (q.options.fields) query = query.projection(q.options.fields)
  if (q.options.sort) query = query.sort(q.options.sort)
  if (q.options.skip) query = query.skip(q.options.skip)
  if (q.options.limit) query = query.limit(q.options.limit)
}
const list = await query.exec()
```

***Caveat:*** I have not run this example -- you may experience some turbulence.

**Comment by pbatey** [comment]
After doing some more research, I've found that the `find()` option exposed by [MongoDB NodeJS Driver](https://mongodb.github.io/node-mongodb-native/4.4/) _does_ support the options as returned by **query-to-mongo**.

- The _Find_ method: [https://mongodb.github.io/node-mongodb-native/4.4/interfaces/FindOptions.html#skip]()
- The _FindOptions_ structure: [https://mongodb.github.io/node-mongodb-native/4.4/interfaces/FindOptions.html]()
- The _skip_ option: [https://mongodb.github.io/node-mongodb-native/4.4/interfaces/FindOptions.html#skip]()

But I did fix the problem you pointed out in the document: `offset` in returned object should be `skip`.
